export interface N8nAgent {
  id: string
  name: string
  slug: string
  category: string
  categorySlug: string
  description: string
  integrations: string[]
  useCases: string[]
  complexity: 'Básico' | 'Intermedio' | 'Avanzado'
  tags: string[]
  isPremium?: boolean
}

export const N8N_CATEGORIES = [
  { id: 'todos', label: 'Todos' },
  { id: 'ventas-leads', label: 'Ventas & Leads' },
  { id: 'whatsapp', label: 'WhatsApp' },
  { id: 'email', label: 'Email & Gmail' },
  { id: 'social-media', label: 'Redes Sociales' },
  { id: 'telegram', label: 'Telegram' },
  { id: 'ia-modelos', label: 'IA & Modelos' },
  { id: 'documentos', label: 'Documentos & PDF' },
  { id: 'google-workspace', label: 'Google Workspace' },
  { id: 'rrhh', label: 'RRHH' },
  { id: 'productividad', label: 'Productividad' },
]

export const N8N_CATALOG: N8nAgent[] = [
  // ── VENTAS & LEADS ────────────────────────────────────────────────────
  {
    id: 'outbound-lead-qualifier',
    name: 'Outbound Lead Qualifier',
    slug: 'outbound-lead-qualifier',
    category: 'Ventas & Leads',
    categorySlug: 'ventas-leads',
    description: 'Califica leads B2B automáticamente mediante análisis IA de perfiles de empresa. Detecta oportunidades de venta y prioriza contactos según criterios personalizados.',
    integrations: ['OpenAI', 'Google Sheets', 'Airtable', 'Gmail'],
    useCases: ['Calificación de leads B2B', 'Scoring automático', 'Priorización de contactos'],
    complexity: 'Intermedio',
    tags: ['ventas', 'leads', 'b2b', 'calificación'],
    isPremium: true,
  },
  {
    id: 'lead-qualification-routing',
    name: 'Lead Qualification & Routing Agent',
    slug: 'lead-qualification-routing',
    category: 'Ventas & Leads',
    categorySlug: 'ventas-leads',
    description: 'Clasifica leads entrantes por puntuación, intención de compra y perfil, luego los enruta automáticamente al vendedor o flujo correspondiente.',
    integrations: ['OpenAI', 'CRM', 'Gmail', 'Slack'],
    useCases: ['Clasificación de leads', 'Enrutamiento a vendedores', 'Scoring con IA'],
    complexity: 'Avanzado',
    tags: ['ventas', 'leads', 'routing', 'crm'],
    isPremium: true,
  },
  {
    id: 'customer-data-enrichment',
    name: 'Customer Data Enrichment Agent',
    slug: 'customer-data-enrichment',
    category: 'Ventas & Leads',
    categorySlug: 'ventas-leads',
    description: 'Enriquece automáticamente datos de contactos y empresas usando múltiples fuentes. Completa emails, teléfonos, industria y tamaño de empresa.',
    integrations: ['Airtable', 'Google Sheets', 'OpenAI', 'HTTP Requests'],
    useCases: ['Enriquecimiento de CRM', 'Completar datos de contacto', 'Investigación de empresas'],
    complexity: 'Intermedio',
    tags: ['crm', 'datos', 'enriquecimiento', 'leads'],
    isPremium: true,
  },
  {
    id: 'marketplace-inquiry-handler',
    name: 'Marketplace Inquiry Handler Agent',
    slug: 'marketplace-inquiry-handler',
    category: 'Ventas & Leads',
    categorySlug: 'ventas-leads',
    description: 'Gestiona consultas entrantes de marketplaces (MercadoLibre, Shopify, etc.) con respuestas automáticas personalizadas y seguimiento de estado de pedidos.',
    integrations: ['MercadoLibre API', 'OpenAI', 'WhatsApp', 'Google Sheets'],
    useCases: ['Atención en MercadoLibre', 'Respuestas automáticas', 'Seguimiento de pedidos'],
    complexity: 'Avanzado',
    tags: ['marketplace', 'ecommerce', 'ventas', 'consultas'],
    isPremium: true,
  },
  {
    id: 'automated-followup',
    name: 'Automated Follow-Up Agent',
    slug: 'automated-followup',
    category: 'Ventas & Leads',
    categorySlug: 'ventas-leads',
    description: 'Automatiza el seguimiento de prospectos y clientes con mensajes personalizados por email y WhatsApp, en el momento exacto con el mensaje correcto.',
    integrations: ['Gmail', 'WhatsApp', 'OpenAI', 'Google Sheets'],
    useCases: ['Seguimiento de prospectos', 'Re-engagement de clientes', 'Pipeline de ventas'],
    complexity: 'Intermedio',
    tags: ['ventas', 'seguimiento', 'email', 'whatsapp'],
    isPremium: true,
  },
  {
    id: 'ai-web-researcher-sales',
    name: 'AI Web Researcher for Sales',
    slug: 'ai-web-researcher-sales',
    category: 'Ventas & Leads',
    categorySlug: 'ventas-leads',
    description: 'Investiga prospectos antes de llamadas o reuniones: extrae información de empresa, noticias recientes, LinkedIn y señales de compra.',
    integrations: ['OpenAI', 'Jina AI', 'Google Sheets', 'SerpAPI'],
    useCases: ['Investigación de prospectos', 'Preparación de reuniones', 'Inteligencia de ventas'],
    complexity: 'Intermedio',
    tags: ['ventas', 'investigación', 'prospectos', 'ia'],
  },
  {
    id: 'qualify-leads-gsheets',
    name: 'Qualify Leads en Google Sheets con GPT-4',
    slug: 'qualify-leads-gsheets',
    category: 'Ventas & Leads',
    categorySlug: 'ventas-leads',
    description: 'Toma una lista de leads en Google Sheets y los califica automáticamente con GPT-4, clasificando por potencial de conversión.',
    integrations: ['Google Sheets', 'OpenAI GPT-4'],
    useCases: ['Calificación masiva de leads', 'Priorización de ventas', 'Análisis de pipeline'],
    complexity: 'Básico',
    tags: ['leads', 'google-sheets', 'gpt-4', 'calificación'],
  },
  {
    id: 'automate-linkedin-outreach',
    name: 'Automate LinkedIn Outreach',
    slug: 'automate-linkedin-outreach',
    category: 'Ventas & Leads',
    categorySlug: 'ventas-leads',
    description: 'Automatiza la prospección en LinkedIn usando Notion como base de datos y OpenAI para personalizar cada mensaje de conexión.',
    integrations: ['LinkedIn', 'Notion', 'OpenAI'],
    useCases: ['Prospección B2B', 'Mensajes personalizados', 'Networking automatizado'],
    complexity: 'Avanzado',
    tags: ['linkedin', 'prospección', 'b2b', 'outreach'],
  },

  // ── WHATSAPP ─────────────────────────────────────────────────────────
  {
    id: 'whatsapp-business-conversation',
    name: 'WhatsApp Business Conversation Agent',
    slug: 'whatsapp-business-conversation',
    category: 'WhatsApp & Mensajería',
    categorySlug: 'whatsapp',
    description: 'Agente conversacional completo para WhatsApp Business: atiende consultas, califica leads, muestra catálogo y redirige a vendedores según intención de compra.',
    integrations: ['WhatsApp Business API', 'OpenAI', 'Airtable', 'Google Sheets'],
    useCases: ['Atención 24/7 en WhatsApp', 'Calificación de leads', 'Mostrar catálogo', 'Cierre de ventas'],
    complexity: 'Avanzado',
    tags: ['whatsapp', 'ventas', 'chatbot', 'atención'],
    isPremium: true,
  },
  {
    id: 'whatsapp-chatbot-basic',
    name: 'WhatsApp Chatbot (Primeros Pasos)',
    slug: 'whatsapp-chatbot-basic',
    category: 'WhatsApp & Mensajería',
    categorySlug: 'whatsapp',
    description: 'Bot básico para WhatsApp que responde preguntas frecuentes, proporciona información de productos y redirige a un agente humano cuando es necesario.',
    integrations: ['WhatsApp Business API', 'n8n Webhook'],
    useCases: ['FAQ automatizadas', 'Información de productos', 'Horarios y precios'],
    complexity: 'Básico',
    tags: ['whatsapp', 'chatbot', 'faq', 'básico'],
  },
  {
    id: 'whatsapp-rag-chatbot',
    name: 'WhatsApp RAG Chatbot con OpenAI',
    slug: 'whatsapp-rag-chatbot',
    category: 'WhatsApp & Mensajería',
    categorySlug: 'whatsapp',
    description: 'Chatbot empresarial completo en WhatsApp con tecnología RAG: responde preguntas sobre tus documentos, catálogos y base de conocimiento con precisión total.',
    integrations: ['WhatsApp Business API', 'OpenAI', 'Pinecone', 'Google Drive'],
    useCases: ['Soporte con base de conocimiento', 'Consultas sobre catálogo', 'FAQ inteligente'],
    complexity: 'Avanzado',
    tags: ['whatsapp', 'rag', 'openai', 'base-conocimiento'],
    isPremium: true,
  },
  {
    id: 'whatsapp-ai-responder',
    name: 'Respond to WhatsApp with AI',
    slug: 'whatsapp-ai-responder',
    category: 'WhatsApp & Mensajería',
    categorySlug: 'whatsapp',
    description: 'Responde mensajes de WhatsApp con IA en tiempo real, con contexto de conversación y capacidad de consultar bases de datos externas.',
    integrations: ['WhatsApp Business API', 'OpenAI', 'Google Sheets'],
    useCases: ['Atención al cliente', 'Respuestas inteligentes', 'Soporte automatizado'],
    complexity: 'Intermedio',
    tags: ['whatsapp', 'ia', 'respuestas', 'automatización'],
  },
  {
    id: 'whatsapp-sales-meeting-prep',
    name: 'Sales Meeting Prep + WhatsApp',
    slug: 'whatsapp-sales-meeting-prep',
    category: 'WhatsApp & Mensajería',
    categorySlug: 'whatsapp',
    description: 'Investiga prospectos automáticamente con APIFY y envía el resumen de preparación de reunión directo a WhatsApp antes de cada llamada.',
    integrations: ['WhatsApp', 'APIFY', 'OpenAI', 'Google Calendar'],
    useCases: ['Preparación de reuniones', 'Investigación de prospectos', 'Briefings de ventas'],
    complexity: 'Intermedio',
    tags: ['whatsapp', 'ventas', 'reuniones', 'investigación'],
  },

  // ── EMAIL & GMAIL ─────────────────────────────────────────────────────
  {
    id: 'gmail-ai-autoresponder',
    name: 'Gmail AI Auto-Responder (Draft Replies)',
    slug: 'gmail-ai-autoresponder',
    category: 'Email & Gmail',
    categorySlug: 'email',
    description: 'Genera borradores de respuesta automáticos en Gmail usando IA, analizando el contexto del email y tu historial para crear respuestas coherentes y profesionales.',
    integrations: ['Gmail', 'OpenAI'],
    useCases: ['Borradores automáticos', 'Respuesta a consultas', 'Ahorro de tiempo en email'],
    complexity: 'Básico',
    tags: ['gmail', 'email', 'ia', 'borradores'],
  },
  {
    id: 'auto-label-gmail',
    name: 'Auto-label Gmail con IA',
    slug: 'auto-label-gmail',
    category: 'Email & Gmail',
    categorySlug: 'email',
    description: 'Etiqueta automáticamente todos los emails entrantes en Gmail usando IA, clasificándolos por urgencia, tipo y acción requerida.',
    integrations: ['Gmail', 'OpenAI'],
    useCases: ['Organización de inbox', 'Clasificación automática', 'Priorización de emails'],
    complexity: 'Básico',
    tags: ['gmail', 'etiquetas', 'organización', 'ia'],
  },
  {
    id: 'email-summary-agent',
    name: 'Email Summary Agent',
    slug: 'email-summary-agent',
    category: 'Email & Gmail',
    categorySlug: 'email',
    description: 'Genera un resumen diario de los emails más importantes, destacando acciones requeridas, fechas límite y oportunidades críticas.',
    integrations: ['Gmail', 'OpenAI', 'Slack', 'Telegram'],
    useCases: ['Resumen diario de inbox', 'Acciones requeridas', 'Inbox zero'],
    complexity: 'Básico',
    tags: ['email', 'resumen', 'productividad', 'diario'],
  },
  {
    id: 'analyze-suspicious-email',
    name: 'Analyze Suspicious Email con ChatGPT',
    slug: 'analyze-suspicious-email',
    category: 'Email & Gmail',
    categorySlug: 'email',
    description: 'Detecta intentos de phishing, spam y emails maliciosos usando ChatGPT Vision, analizando contenido, remitente y adjuntos.',
    integrations: ['Gmail', 'OpenAI ChatGPT', 'Slack'],
    useCases: ['Seguridad de email', 'Detección de phishing', 'Análisis de amenazas'],
    complexity: 'Intermedio',
    tags: ['seguridad', 'phishing', 'gmail', 'chatgpt'],
  },
  {
    id: 'effortless-email-management',
    name: 'Effortless Email Management (AI Review)',
    slug: 'effortless-email-management',
    category: 'Email & Gmail',
    categorySlug: 'email',
    description: 'Sistema completo de gestión de email: resume, prioriza, sugiere respuestas y lleva un registro de comunicaciones importantes por cliente.',
    integrations: ['Gmail', 'OpenAI', 'Google Sheets', 'Airtable'],
    useCases: ['Gestión completa de inbox', 'Priorización inteligente', 'CRM de comunicaciones'],
    complexity: 'Avanzado',
    tags: ['email', 'gestión', 'productividad', 'ia'],
  },
  {
    id: 'gmail-spending-to-sheets',
    name: 'Extract Gastos de Gmail a Google Sheets',
    slug: 'gmail-spending-to-sheets',
    category: 'Email & Gmail',
    categorySlug: 'email',
    description: 'Extrae automáticamente información de gastos de emails de compras y facturas, registrándolos en Google Sheets para control financiero.',
    integrations: ['Gmail', 'Google Sheets', 'OpenAI'],
    useCases: ['Control de gastos', 'Contabilidad automática', 'Seguimiento de facturas'],
    complexity: 'Básico',
    tags: ['gmail', 'gastos', 'finanzas', 'google-sheets'],
  },
  {
    id: 'auto-categorize-outlook',
    name: 'Auto-Categorize Outlook Emails con IA',
    slug: 'auto-categorize-outlook',
    category: 'Email & Gmail',
    categorySlug: 'email',
    description: 'Categoriza automáticamente emails de Microsoft Outlook con IA, organizando por proyecto, cliente o urgencia según reglas personalizadas.',
    integrations: ['Microsoft Outlook', 'OpenAI', 'Microsoft 365'],
    useCases: ['Organización Outlook', 'Clasificación por proyecto', 'Gestión empresarial'],
    complexity: 'Intermedio',
    tags: ['outlook', 'microsoft', 'email', 'categorización'],
  },
  {
    id: 'gmail-chatgpt-reply-sheets',
    name: 'ChatGPT Email Reply + Google Sheets Log',
    slug: 'gmail-chatgpt-reply-sheets',
    category: 'Email & Gmail',
    categorySlug: 'email',
    description: 'Responde emails automáticamente con ChatGPT y registra todas las interacciones en Google Sheets para seguimiento y análisis.',
    integrations: ['Gmail', 'OpenAI ChatGPT', 'Google Sheets'],
    useCases: ['Respuestas automáticas', 'Registro de comunicaciones', 'Análisis de emails'],
    complexity: 'Básico',
    tags: ['gmail', 'chatgpt', 'google-sheets', 'respuestas'],
  },

  // ── REDES SOCIALES ────────────────────────────────────────────────────
  {
    id: 'social-media-content-publisher',
    name: 'Social Media Content Publisher Agent',
    slug: 'social-media-content-publisher',
    category: 'Redes Sociales',
    categorySlug: 'social-media',
    description: 'Publica contenido automáticamente en Facebook Fanpage e Instagram según un calendario en Google Sheets, con optimización de horarios y hashtags.',
    integrations: ['Meta Graph API', 'Google Sheets', 'Airtable', 'OpenAI'],
    useCases: ['Publicación Facebook/Instagram', 'Calendario de contenido', 'Gestión de fanpage'],
    complexity: 'Avanzado',
    tags: ['facebook', 'instagram', 'social-media', 'publicación'],
    isPremium: true,
  },
  {
    id: 'facebook-messenger-lead-capture',
    name: 'Facebook Messenger Lead Capture Agent',
    slug: 'facebook-messenger-lead-capture',
    category: 'Redes Sociales',
    categorySlug: 'social-media',
    description: 'Captura y califica leads en Facebook Messenger, detecta intención de compra y redirige estratégicamente a WhatsApp para el cierre de ventas.',
    integrations: ['Meta Graph API', 'OpenAI', 'Airtable', 'WhatsApp'],
    useCases: ['Captura de leads en Messenger', 'Calificación automática', 'Redirección a WhatsApp'],
    complexity: 'Avanzado',
    tags: ['facebook', 'messenger', 'leads', 'ventas'],
    isPremium: true,
  },
  {
    id: 'social-media-master-coordinator',
    name: 'Social Media Master Coordinator',
    slug: 'social-media-master-coordinator',
    category: 'Redes Sociales',
    categorySlug: 'social-media',
    description: 'Coordina todas las plataformas sociales desde un único flujo: programa, publica, monitorea engagement y genera reportes de rendimiento.',
    integrations: ['Meta Graph API', 'Twitter API', 'Google Sheets', 'OpenAI', 'Slack'],
    useCases: ['Gestión multi-plataforma', 'Reportes de engagement', 'Calendario unificado'],
    complexity: 'Avanzado',
    tags: ['redes-sociales', 'coordinación', 'multi-plataforma', 'reportes'],
    isPremium: true,
  },
  {
    id: 'ai-social-media-amplifier',
    name: 'AI Social Media Amplifier',
    slug: 'ai-social-media-amplifier',
    category: 'Redes Sociales',
    categorySlug: 'social-media',
    description: 'Amplifica el alcance del contenido existente transformándolo para diferentes redes sociales con IA: adapta formato, tono y hashtags por plataforma.',
    integrations: ['OpenAI', 'Twitter', 'LinkedIn', 'Facebook', 'Instagram'],
    useCases: ['Repurposing de contenido', 'Adaptación multi-plataforma', 'Maximizar alcance'],
    complexity: 'Intermedio',
    tags: ['social-media', 'contenido', 'ia', 'alcance'],
  },
  {
    id: 'instagram-content-from-trends',
    name: 'Genera Contenido Instagram desde Tendencias',
    slug: 'instagram-content-from-trends',
    category: 'Redes Sociales',
    categorySlug: 'social-media',
    description: 'Detecta tendencias actuales y genera automáticamente contenido visual y captions optimizados para Instagram usando IA generativa.',
    integrations: ['Instagram Graph API', 'OpenAI', 'DALL-E', 'Google Trends'],
    useCases: ['Contenido en tendencias', 'Posts automáticos', 'Estrategia viral'],
    complexity: 'Intermedio',
    tags: ['instagram', 'tendencias', 'contenido', 'ia'],
  },
  {
    id: 'twitter-virtual-influencer',
    name: 'Twitter Virtual AI Influencer',
    slug: 'twitter-virtual-influencer',
    category: 'Redes Sociales',
    categorySlug: 'social-media',
    description: 'Crea y gestiona una presencia activa en Twitter con tweets generados por IA, respuestas automáticas y estrategia de crecimiento de audiencia.',
    integrations: ['Twitter API', 'OpenAI', 'Google Sheets'],
    useCases: ['Gestión automatizada Twitter', 'Crecimiento de audiencia', 'Content marketing'],
    complexity: 'Intermedio',
    tags: ['twitter', 'influencer', 'ia', 'automatización'],
  },
  {
    id: 'ai-videos-social-media',
    name: 'Generate & Auto-post AI Videos (Veo3 + Blotato)',
    slug: 'ai-videos-social-media',
    category: 'Redes Sociales',
    categorySlug: 'social-media',
    description: 'Genera videos con IA usando Google Veo3 y los publica automáticamente en Instagram, TikTok y YouTube vía Blotato.',
    integrations: ['Google Veo3', 'Blotato', 'Instagram', 'TikTok', 'YouTube'],
    useCases: ['Videos IA automáticos', 'Publicación multi-plataforma', 'Marketing en video'],
    complexity: 'Avanzado',
    tags: ['video', 'ia', 'instagram', 'tiktok', 'veo3'],
    isPremium: true,
  },
  {
    id: 'post-youtube-to-twitter',
    name: 'Post YouTube Videos a X (Twitter) Auto',
    slug: 'post-youtube-to-twitter',
    category: 'Redes Sociales',
    categorySlug: 'social-media',
    description: 'Detecta nuevos videos publicados en YouTube y los comparte automáticamente en X (Twitter) con un caption generado por IA.',
    integrations: ['YouTube API', 'Twitter/X API', 'OpenAI'],
    useCases: ['Cross-posting automático', 'Distribución de contenido', 'Crecimiento multi-canal'],
    complexity: 'Básico',
    tags: ['youtube', 'twitter', 'cross-posting', 'automatización'],
  },
  {
    id: 'social-media-analysis-email',
    name: 'Social Media Analysis + Email Report',
    slug: 'social-media-analysis-email',
    category: 'Redes Sociales',
    categorySlug: 'social-media',
    description: 'Analiza el rendimiento de todas las redes sociales y genera reportes automáticos por email con insights y recomendaciones de IA.',
    integrations: ['Meta API', 'Twitter API', 'OpenAI', 'Gmail'],
    useCases: ['Reportes de rendimiento', 'Análisis de engagement', 'Insights automáticos'],
    complexity: 'Intermedio',
    tags: ['análisis', 'reportes', 'social-media', 'email'],
  },

  // ── TELEGRAM ─────────────────────────────────────────────────────────
  {
    id: 'telegram-ai-chatbot',
    name: 'Telegram AI Chatbot',
    slug: 'telegram-ai-chatbot',
    category: 'Telegram',
    categorySlug: 'telegram',
    description: 'Bot de IA completo para Telegram que responde preguntas, ejecuta tareas y se integra con servicios externos de forma autónoma.',
    integrations: ['Telegram Bot API', 'OpenAI', 'n8n Webhooks'],
    useCases: ['Asistente en Telegram', 'Respuestas automáticas', 'Automatización por chat'],
    complexity: 'Básico',
    tags: ['telegram', 'chatbot', 'ia', 'bot'],
  },
  {
    id: 'telegram-ai-long-term-memory',
    name: 'AI Chatbot + Memoria a Largo Plazo (Telegram)',
    slug: 'telegram-ai-long-term-memory',
    category: 'Telegram',
    categorySlug: 'telegram',
    description: 'Bot de Telegram con memoria persistente: recuerda conversaciones pasadas, notas del usuario y contexto histórico para respuestas cada vez más inteligentes.',
    integrations: ['Telegram Bot API', 'OpenAI', 'Supabase', 'PostgreSQL'],
    useCases: ['Asistente con memoria', 'Gestión de notas', 'Contexto persistente'],
    complexity: 'Avanzado',
    tags: ['telegram', 'memoria', 'ia', 'langchain'],
    isPremium: true,
  },
  {
    id: 'deepseek-telegram-memory',
    name: 'DeepSeek AI Agent + Telegram + Memoria',
    slug: 'deepseek-telegram-memory',
    category: 'Telegram',
    categorySlug: 'telegram',
    description: 'Agente IA con DeepSeek V3 en Telegram y memoria de largo plazo. Alternativa de bajo costo a GPT-4 con alto rendimiento en español.',
    integrations: ['Telegram Bot API', 'DeepSeek AI', 'PostgreSQL', 'n8n'],
    useCases: ['Asistente low-cost', 'Chat con memoria', 'Automatización en español'],
    complexity: 'Avanzado',
    tags: ['telegram', 'deepseek', 'memoria', 'ia-local'],
    isPremium: true,
  },
  {
    id: 'telegram-voice-text-assistant',
    name: 'Angie — Asistente Personal Voz & Texto',
    slug: 'telegram-voice-text-assistant',
    category: 'Telegram',
    categorySlug: 'telegram',
    description: 'Asistente personal en Telegram que entiende mensajes de voz y texto, gestiona tareas, busca información y responde en audio o texto.',
    integrations: ['Telegram', 'OpenAI Whisper', 'OpenAI GPT-4', 'ElevenLabs'],
    useCases: ['Asistente personal', 'Notas por voz', 'Gestión de tareas'],
    complexity: 'Avanzado',
    tags: ['telegram', 'voz', 'asistente', 'whisper'],
  },
  {
    id: 'telegram-multimedia-agent',
    name: 'Telegram Agent Multimedia (Texto/Audio/Imagen)',
    slug: 'telegram-multimedia-agent',
    category: 'Telegram',
    categorySlug: 'telegram',
    description: 'Agente multimodal para Telegram que procesa texto, audios e imágenes, ejecutando acciones diferentes según el tipo de contenido recibido.',
    integrations: ['Telegram', 'OpenAI', 'OpenAI Whisper', 'OpenAI Vision'],
    useCases: ['Bot multimedia', 'Procesamiento de imágenes', 'Transcripción de audio'],
    complexity: 'Avanzado',
    tags: ['telegram', 'multimedia', 'visión', 'audio'],
    isPremium: true,
  },
  {
    id: 'telegram-langchain-bot',
    name: 'Telegram AI Bot con LangChain',
    slug: 'telegram-langchain-bot',
    category: 'Telegram',
    categorySlug: 'telegram',
    description: 'Bot avanzado con LangChain: usa herramientas externas (búsqueda web, calculadora, APIs), razona paso a paso y ejecuta acciones complejas.',
    integrations: ['Telegram', 'LangChain', 'OpenAI', 'SerpAPI'],
    useCases: ['Agente con herramientas', 'Búsqueda web', 'Razonamiento complejo'],
    complexity: 'Avanzado',
    tags: ['telegram', 'langchain', 'agente', 'herramientas'],
  },
  {
    id: 'telegram-pdf-chat',
    name: 'Telegram: Chat con PDF',
    slug: 'telegram-pdf-chat',
    category: 'Telegram',
    categorySlug: 'telegram',
    description: 'Envía cualquier PDF a Telegram y chatea con él: hace preguntas, extrae información específica y genera resúmenes instantáneos.',
    integrations: ['Telegram', 'OpenAI', 'LangChain'],
    useCases: ['Chat con documentos', 'Extracción de información', 'Análisis de PDF'],
    complexity: 'Intermedio',
    tags: ['telegram', 'pdf', 'chat', 'documentos'],
  },
  {
    id: 'telegram-audio-translator',
    name: 'Traductor de Audio Telegram (55 idiomas)',
    slug: 'telegram-audio-translator',
    category: 'Telegram',
    categorySlug: 'telegram',
    description: 'Traduce mensajes de audio de Telegram en tiempo real a cualquiera de 55 idiomas usando IA, perfecto para equipos internacionales.',
    integrations: ['Telegram', 'OpenAI Whisper', 'OpenAI'],
    useCases: ['Traducción en tiempo real', 'Transcripción de audio', 'Comunicación multilingüe'],
    complexity: 'Básico',
    tags: ['telegram', 'traducción', 'audio', 'idiomas'],
  },
  {
    id: 'telegram-supabase-memory',
    name: 'Telegram Bot + Supabase + OpenAI Assistant',
    slug: 'telegram-supabase-memory',
    category: 'Telegram',
    categorySlug: 'telegram',
    description: 'Bot de Telegram respaldado por Supabase para historial de conversaciones y OpenAI Assistant para respuestas contextuales.',
    integrations: ['Telegram', 'Supabase', 'OpenAI Assistant'],
    useCases: ['Historial persistente', 'Asistente empresarial', 'Base de conocimiento'],
    complexity: 'Intermedio',
    tags: ['telegram', 'supabase', 'openai', 'memoria'],
  },

  // ── IA & MODELOS ─────────────────────────────────────────────────────
  {
    id: 'agente-secretario',
    name: 'Agente Secretario IA',
    slug: 'agente-secretario',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Asistente ejecutivo completo: gestiona calendario, redacta emails, agenda reuniones, busca información y coordina tareas como un secretario virtual profesional.',
    integrations: ['OpenAI', 'Google Calendar', 'Gmail', 'Google Drive'],
    useCases: ['Secretaría virtual', 'Gestión de agenda', 'Redacción de emails', 'Coordinación de reuniones'],
    complexity: 'Avanzado',
    tags: ['secretario', 'ia', 'productividad', 'asistente'],
    isPremium: true,
  },
  {
    id: 'agente-secretario-telegram',
    name: 'Agente Secretario via Telegram (OpenRouter)',
    slug: 'agente-secretario-telegram',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Secretario IA accesible via Telegram usando OpenRouter para selección del mejor modelo según la tarea. Integrado con calendarios y correo.',
    integrations: ['Telegram', 'OpenRouter', 'Google Calendar', 'Gmail'],
    useCases: ['Secretario en Telegram', 'Modelos flexibles', 'Gestión de agenda'],
    complexity: 'Avanzado',
    tags: ['telegram', 'secretario', 'openrouter', 'ia'],
    isPremium: true,
  },
  {
    id: 'ultimate-personal-assistant',
    name: 'Ultimate Personal Assistant',
    slug: 'ultimate-personal-assistant',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'El asistente personal más completo: maneja email, calendario, tareas, recordatorios, búsquedas, notas y comunicaciones desde una única interfaz.',
    integrations: ['OpenAI', 'Gmail', 'Google Calendar', 'Notion', 'Slack', 'WhatsApp'],
    useCases: ['Asistente personal completo', 'Productividad total', 'Gestión de vida digital'],
    complexity: 'Avanzado',
    tags: ['asistente', 'productividad', 'ia', 'completo'],
    isPremium: true,
  },
  {
    id: 'calendar-agent',
    name: 'Calendar Agent IA',
    slug: 'calendar-agent',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Gestiona tu Google Calendar con lenguaje natural: agenda reuniones, encuentra disponibilidad, reagenda eventos y envía invitaciones automáticamente.',
    integrations: ['Google Calendar', 'OpenAI', 'Gmail'],
    useCases: ['Agendamiento automático', 'Gestión de reuniones', 'Coordinación de equipo'],
    complexity: 'Intermedio',
    tags: ['calendario', 'ia', 'reuniones', 'google-calendar'],
    isPremium: true,
  },
  {
    id: 'email-agent-ia',
    name: 'Email Agent IA',
    slug: 'email-agent-ia',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Agente especializado en email: redacta, responde, clasifica y gestiona toda la comunicación por correo con instrucciones en lenguaje natural.',
    integrations: ['Gmail', 'OpenAI', 'Airtable'],
    useCases: ['Gestión de email', 'Redacción automática', 'Clasificación inteligente'],
    complexity: 'Intermedio',
    tags: ['email', 'agente', 'ia', 'gmail'],
    isPremium: true,
  },
  {
    id: 'content-creator-agent',
    name: 'Content Creator Agent IA',
    slug: 'content-creator-agent',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Crea contenido de alta calidad para blogs, redes sociales, emails y más: artículos, posts, descripciones de producto y copies publicitarios.',
    integrations: ['OpenAI', 'Google Docs', 'Airtable', 'WordPress'],
    useCases: ['Creación de contenido', 'Copywriting', 'Blog posts', 'Social media'],
    complexity: 'Intermedio',
    tags: ['contenido', 'copywriting', 'ia', 'marketing'],
    isPremium: true,
  },
  {
    id: 'ai-voice-chat',
    name: 'AI Voice Chat (ElevenLabs + OpenAI)',
    slug: 'ai-voice-chat',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Sistema de chat por voz con IA: habla con el agente y recibe respuestas en audio con voces realistas usando ElevenLabs y GPT-4.',
    integrations: ['OpenAI GPT-4', 'ElevenLabs', 'OpenAI Whisper', 'Google Gemini'],
    useCases: ['Asistente por voz', 'Atención al cliente por audio', 'Voice UX'],
    complexity: 'Avanzado',
    tags: ['voz', 'audio', 'elevenlabs', 'ia'],
  },
  {
    id: 'youtube-video-summarizer',
    name: 'YouTube Video Summarizer',
    slug: 'youtube-video-summarizer',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Transcribe y resume automáticamente videos de YouTube: extrae puntos clave, citas importantes y acciones requeridas en minutos.',
    integrations: ['YouTube API', 'OpenAI', 'Telegram', 'Notion'],
    useCases: ['Resumen de videos', 'Aprendizaje eficiente', 'Investigación de contenido'],
    complexity: 'Básico',
    tags: ['youtube', 'resumen', 'transcripción', 'ia'],
  },
  {
    id: 'flux-ai-image-generator',
    name: 'FLUX AI Image Generator',
    slug: 'flux-ai-image-generator',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Genera imágenes profesionales de alta calidad usando FLUX.1 con interfaz de prompts personalizable. El modelo de imagen más avanzado.',
    integrations: ['FLUX.1 (fal.ai)', 'n8n', 'Google Drive', 'Telegram'],
    useCases: ['Generación de imágenes IA', 'Marketing visual', 'Diseño automatizado'],
    complexity: 'Básico',
    tags: ['imágenes', 'flux', 'ia-generativa', 'diseño'],
  },
  {
    id: 'deepseek-chat',
    name: 'DeepSeek Chat V3 + R1 Reasoning',
    slug: 'deepseek-chat',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Accede a DeepSeek V3 para chat general y DeepSeek R1 para razonamiento complejo: la alternativa más potente y económica a GPT-4.',
    integrations: ['DeepSeek API', 'n8n', 'Webhook'],
    useCases: ['Chat inteligente', 'Razonamiento complejo', 'Análisis de datos'],
    complexity: 'Básico',
    tags: ['deepseek', 'ia', 'chat', 'razonamiento'],
  },
  {
    id: 'private-local-ai-ollama',
    name: 'Asistente IA Privado y Local (Ollama)',
    slug: 'private-local-ai-ollama',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Despliega tu propio modelo de IA 100% privado con Ollama: sin enviar datos a terceros, sin costos por token, con control total.',
    integrations: ['Ollama', 'n8n', 'Llama 3', 'Mistral'],
    useCases: ['IA privada', 'Datos sensibles', 'Sin costos de API', 'On-premise'],
    complexity: 'Avanzado',
    tags: ['ollama', 'privado', 'local', 'ia-local'],
  },
  {
    id: 'multi-channel-analytics',
    name: 'Multi-Channel Analytics Agent',
    slug: 'multi-channel-analytics',
    category: 'IA & Modelos',
    categorySlug: 'ia-modelos',
    description: 'Agrega métricas de todos los canales digitales (social, email, web, ads) y genera reportes automáticos con insights y recomendaciones de IA.',
    integrations: ['Google Analytics', 'Meta Ads', 'Google Sheets', 'OpenAI', 'Slack'],
    useCases: ['Dashboard unificado', 'Reportes automáticos', 'Análisis multi-canal'],
    complexity: 'Avanzado',
    tags: ['analytics', 'reportes', 'multi-canal', 'ia'],
    isPremium: true,
  },

  // ── DOCUMENTOS & PDF ─────────────────────────────────────────────────
  {
    id: 'chat-with-pdf',
    name: 'Chat con PDF usando IA',
    slug: 'chat-with-pdf',
    category: 'Documentos & PDF',
    categorySlug: 'documentos',
    description: 'Carga cualquier PDF y chatea con él: hace preguntas sobre el contenido, extrae datos específicos y cita las fuentes exactas de sus respuestas.',
    integrations: ['OpenAI', 'LangChain', 'Supabase', 'n8n'],
    useCases: ['Chat con contratos', 'Extracción de datos', 'Análisis de documentos'],
    complexity: 'Básico',
    tags: ['pdf', 'chat', 'documentos', 'ia'],
  },
  {
    id: 'invoice-extraction-llamaparse',
    name: 'Extracción de Facturas con LlamaParse + OpenAI',
    slug: 'invoice-extraction-llamaparse',
    category: 'Documentos & PDF',
    categorySlug: 'documentos',
    description: 'Extrae automáticamente todos los datos de facturas (fecha, proveedor, items, totales, CUIT) y los registra en Airtable o Google Sheets.',
    integrations: ['LlamaParse', 'OpenAI', 'Airtable', 'Google Sheets'],
    useCases: ['Automatización de facturas', 'Contabilidad automática', 'Control de gastos'],
    complexity: 'Intermedio',
    tags: ['facturas', 'pdf', 'extracción', 'contabilidad'],
    isPremium: true,
  },
  {
    id: 'cv-pdf-parsing',
    name: 'CV/Resume PDF Parser (Visión IA Multimodal)',
    slug: 'cv-pdf-parsing',
    category: 'Documentos & PDF',
    categorySlug: 'documentos',
    description: 'Analiza CVs en PDF con visión IA multimodal: extrae nombre, experiencia, skills, formación y genera perfil estructurado en segundos.',
    integrations: ['OpenAI Vision', 'LlamaParse', 'Airtable', 'Google Sheets'],
    useCases: ['Screening de candidatos', 'Parsing de CVs', 'Base de datos de talento'],
    complexity: 'Intermedio',
    tags: ['cv', 'pdf', 'rrhh', 'visión-ia'],
  },
  {
    id: 'pdf-to-csv-vertex',
    name: 'Extract Texto de PDF a CSV (Gemini Vision)',
    slug: 'pdf-to-csv-vertex',
    category: 'Documentos & PDF',
    categorySlug: 'documentos',
    description: 'Convierte tablas y datos en PDFs e imágenes a formato CSV usando Gemini Vision IA, listo para importar a cualquier sistema.',
    integrations: ['Google Vertex AI', 'Gemini', 'Google Sheets', 'n8n'],
    useCases: ['PDF a Excel/CSV', 'Digitalización de tablas', 'Migración de datos'],
    complexity: 'Intermedio',
    tags: ['pdf', 'csv', 'gemini', 'extracción'],
  },
  {
    id: 'bank-statement-transcription',
    name: 'Digitalizar Extractos Bancarios (Gemini Vision)',
    slug: 'bank-statement-transcription',
    category: 'Documentos & PDF',
    categorySlug: 'documentos',
    description: 'Digitaliza extractos bancarios en PDF o imagen a datos estructurados usando Gemini Vision, facilitando el análisis financiero automatizado.',
    integrations: ['Google Gemini Vision', 'Google Drive', 'Notion'],
    useCases: ['Digitalización bancaria', 'Análisis financiero', 'Contabilidad automatizada'],
    complexity: 'Básico',
    tags: ['bancario', 'pdf', 'gemini', 'finanzas'],
  },
  {
    id: 'ask-questions-pdf',
    name: 'Q&A sobre cualquier Documento PDF',
    slug: 'ask-questions-pdf',
    category: 'Documentos & PDF',
    categorySlug: 'documentos',
    description: 'Sistema de preguntas y respuestas para PDFs: carga el documento, hace la pregunta y recibe respuesta directa con la cita exacta.',
    integrations: ['OpenAI', 'LangChain', 'n8n'],
    useCases: ['Q&A sobre documentos', 'Búsqueda en manuales', 'Análisis de contratos'],
    complexity: 'Básico',
    tags: ['pdf', 'qa', 'preguntas', 'documentos'],
  },

  // ── GOOGLE WORKSPACE ─────────────────────────────────────────────────
  {
    id: 'chat-with-google-sheet',
    name: 'Chat con Google Sheets usando IA',
    slug: 'chat-with-google-sheet',
    category: 'Google Workspace',
    categorySlug: 'google-workspace',
    description: 'Hace preguntas en lenguaje natural sobre los datos de cualquier Google Sheet y recibe respuestas, análisis y resúmenes automáticos.',
    integrations: ['Google Sheets', 'OpenAI', 'LangChain'],
    useCases: ['Análisis de datos sin SQL', 'Reportes conversacionales', 'Consultas de planillas'],
    complexity: 'Básico',
    tags: ['google-sheets', 'chat', 'análisis', 'ia'],
  },
  {
    id: 'rag-company-docs-gemini',
    name: 'RAG Chatbot Documentos Empresa (Drive + Gemini)',
    slug: 'rag-company-docs-gemini',
    category: 'Google Workspace',
    categorySlug: 'google-workspace',
    description: 'Convierte toda la documentación de Google Drive en un chatbot RAG: responde preguntas sobre manuales, procesos y políticas con precisión.',
    integrations: ['Google Drive', 'Google Gemini', 'Pinecone', 'n8n'],
    useCases: ['Base de conocimiento', 'FAQ de procesos', 'Onboarding de empleados'],
    complexity: 'Avanzado',
    tags: ['google-drive', 'rag', 'gemini', 'conocimiento'],
    isPremium: true,
  },
  {
    id: 'author-blog-from-gsheets',
    name: 'Publica Blog Posts desde Google Sheets',
    slug: 'author-blog-from-gsheets',
    category: 'Google Workspace',
    categorySlug: 'google-workspace',
    description: 'Lee títulos y temas de Google Sheets, genera artículos de blog completos con IA y los publica automáticamente en WordPress o Ghost.',
    integrations: ['Google Sheets', 'OpenAI', 'WordPress', 'Ghost CMS'],
    useCases: ['Contenido SEO automático', 'Blog escalable', 'Content marketing'],
    complexity: 'Intermedio',
    tags: ['blog', 'google-sheets', 'wordpress', 'ia'],
  },
  {
    id: 'qualify-leads-gsheets-gpt4',
    name: 'Screen Applicants con IA + Google Sheets',
    slug: 'qualify-leads-gsheets-gpt4',
    category: 'Google Workspace',
    categorySlug: 'google-workspace',
    description: 'Filtra y evalúa postulantes automáticamente: lee CVs o formularios en Google Sheets, puntúa con IA y notifica al equipo RRHH.',
    integrations: ['Google Sheets', 'OpenAI GPT-4', 'Gmail', 'Slack'],
    useCases: ['Filtrado de candidatos', 'Scoring automático', 'Notificaciones RRHH'],
    complexity: 'Básico',
    tags: ['google-sheets', 'rrhh', 'candidatos', 'gpt-4'],
  },
  {
    id: 'summarize-gsheets-feedback',
    name: 'Resume Feedback de Google Sheets con GPT-4',
    slug: 'summarize-gsheets-feedback',
    category: 'Google Workspace',
    categorySlug: 'google-workspace',
    description: 'Analiza respuestas de encuestas o formularios en Google Sheets y genera resúmenes con sentimiento, temas principales y acciones recomendadas.',
    integrations: ['Google Sheets', 'OpenAI GPT-4'],
    useCases: ['Análisis de feedback', 'NPS analysis', 'Mejora de producto'],
    complexity: 'Básico',
    tags: ['feedback', 'google-sheets', 'análisis', 'gpt-4'],
  },
  {
    id: 'vision-ai-scraper-gsheets',
    name: 'Vision AI Scraper (Gemini + Google Sheets)',
    slug: 'vision-ai-scraper-gsheets',
    category: 'Google Workspace',
    categorySlug: 'google-workspace',
    description: 'Extrae datos de webs usando Gemini Vision: captura screenshots, analiza visualmente la página y exporta datos estructurados a Google Sheets.',
    integrations: ['Gemini 2.0', 'Google Sheets', 'ScrapingBee', 'n8n'],
    useCases: ['Web scraping visual', 'Extracción de precios', 'Monitoreo de competencia'],
    complexity: 'Avanzado',
    tags: ['scraping', 'gemini', 'google-sheets', 'visión'],
  },

  // ── RRHH & RECLUTAMIENTO ──────────────────────────────────────────────
  {
    id: 'hr-cv-analysis',
    name: 'HR Workflow Automático — Análisis de CVs',
    slug: 'hr-cv-analysis',
    category: 'RRHH & Reclutamiento',
    categorySlug: 'rrhh',
    description: 'Automatiza todo el flujo de reclutamiento: analiza CVs entrantes, califica candidatos, notifica a RRHH y gestiona comunicaciones con postulantes.',
    integrations: ['Gmail', 'OpenAI', 'Google Sheets', 'Airtable', 'Slack'],
    useCases: ['Screening masivo de CVs', 'Notificaciones RRHH', 'Gestión de candidatos'],
    complexity: 'Avanzado',
    tags: ['rrhh', 'reclutamiento', 'cvs', 'automatización'],
    isPremium: true,
  },
  {
    id: 'cv-screening-openai',
    name: 'CV Screening con OpenAI',
    slug: 'cv-screening-openai',
    category: 'RRHH & Reclutamiento',
    categorySlug: 'rrhh',
    description: 'Procesa CVs en bulk usando OpenAI: puntúa candidatos según criterios del puesto, genera resúmenes comparativos y recomienda los mejores perfiles.',
    integrations: ['OpenAI', 'Google Sheets', 'Gmail'],
    useCases: ['Screening de candidatos', 'Ranking de CVs', 'Decisiones de contratación'],
    complexity: 'Intermedio',
    tags: ['rrhh', 'screening', 'openai', 'cvs'],
  },
  {
    id: 'hr-job-posting-evaluation',
    name: 'HR Job Posting + Evaluación con IA',
    slug: 'hr-job-posting-evaluation',
    category: 'RRHH & Reclutamiento',
    categorySlug: 'rrhh',
    description: 'Crea descripciones de trabajo optimizadas con IA, las publica en múltiples portales y evalúa automáticamente las postulaciones recibidas.',
    integrations: ['OpenAI', 'LinkedIn', 'Google Sheets', 'Gmail'],
    useCases: ['Publicación de empleos', 'Evaluación de postulaciones', 'Gestión de vacantes'],
    complexity: 'Intermedio',
    tags: ['rrhh', 'empleos', 'publicación', 'evaluación'],
  },
  {
    id: 'bamboohr-policies-chatbot',
    name: 'BambooHR Chatbot de Políticas Empresariales',
    slug: 'bamboohr-policies-chatbot',
    category: 'RRHH & Reclutamiento',
    categorySlug: 'rrhh',
    description: 'Chatbot con IA que responde preguntas de empleados sobre políticas de empresa, beneficios y procedimientos, integrado con BambooHR.',
    integrations: ['BambooHR', 'OpenAI', 'Slack', 'Microsoft Teams'],
    useCases: ['FAQ de empleados', 'Políticas de empresa', 'Onboarding automático'],
    complexity: 'Intermedio',
    tags: ['bamboohr', 'rrhh', 'políticas', 'chatbot'],
  },

  // ── PRODUCTIVIDAD ─────────────────────────────────────────────────────
  {
    id: 'notion-ai-assistant',
    name: 'Notion AI Assistant Generator',
    slug: 'notion-ai-assistant',
    category: 'Productividad',
    categorySlug: 'productividad',
    description: 'Genera asistentes IA personalizados para Notion: responde preguntas sobre tus bases de datos, crea páginas y actualiza registros con lenguaje natural.',
    integrations: ['Notion API', 'OpenAI', 'n8n'],
    useCases: ['Asistente en Notion', 'Gestión de bases de datos', 'Automatización Notion'],
    complexity: 'Intermedio',
    tags: ['notion', 'asistente', 'ia', 'productividad'],
  },
  {
    id: 'notion-knowledge-base',
    name: 'Notion Knowledge Base AI Assistant',
    slug: 'notion-knowledge-base',
    category: 'Productividad',
    categorySlug: 'productividad',
    description: 'Convierte tu espacio de Notion en una base de conocimiento inteligente con RAG: hace preguntas y obtiene respuestas precisas de cualquier página.',
    integrations: ['Notion API', 'OpenAI', 'Pinecone'],
    useCases: ['Base de conocimiento', 'Wiki empresarial', 'Q&A sobre Notion'],
    complexity: 'Avanzado',
    tags: ['notion', 'conocimiento', 'rag', 'ia'],
    isPremium: true,
  },
  {
    id: 'competitor-research-notion',
    name: 'Competitor Research Automático (Notion + Exa.ai)',
    slug: 'competitor-research-notion',
    category: 'Productividad',
    categorySlug: 'productividad',
    description: 'Investiga competidores automáticamente: rastrea actualizaciones de producto, precios, contenido y noticias, organizando todo en Notion.',
    integrations: ['Exa.ai', 'Notion', 'OpenAI', 'n8n'],
    useCases: ['Análisis de competidores', 'Market intelligence', 'Monitoreo de industria'],
    complexity: 'Avanzado',
    tags: ['competidores', 'notion', 'investigación', 'ia'],
  },
  {
    id: 'it-ops-slackbot',
    name: 'IT Ops AI SlackBot (Knowledge Base)',
    slug: 'it-ops-slackbot',
    category: 'Productividad',
    categorySlug: 'productividad',
    description: 'Bot de soporte IT en Slack que responde preguntas técnicas, resuelve problemas comunes y escala tickets complejos al equipo correspondiente.',
    integrations: ['Slack', 'OpenAI', 'Linear', 'Google Drive'],
    useCases: ['Soporte IT interno', 'Helpdesk automático', 'Resolución de tickets'],
    complexity: 'Avanzado',
    tags: ['slack', 'it', 'soporte', 'helpdesk'],
  },
  {
    id: 'customer-support-ticketing',
    name: 'Customer Support Ticketing (Slack + Linear)',
    slug: 'customer-support-ticketing',
    category: 'Productividad',
    categorySlug: 'productividad',
    description: 'Sistema de tickets de soporte al cliente integrado con Slack y Linear: crea, asigna, actualiza y cierra tickets con seguimiento automático.',
    integrations: ['Slack', 'Linear', 'OpenAI'],
    useCases: ['Sistema de tickets', 'Soporte al cliente', 'Gestión de incidentes'],
    complexity: 'Intermedio',
    tags: ['slack', 'soporte', 'tickets', 'linear'],
  },
  {
    id: 'slack-gemini-bot',
    name: 'AI Slack Bot con Google Gemini',
    slug: 'slack-gemini-bot',
    category: 'Productividad',
    categorySlug: 'productividad',
    description: 'Bot de IA en Slack usando Google Gemini: responde preguntas del equipo, resume documentos, genera contenido y ejecuta acciones desde el chat.',
    integrations: ['Slack', 'Google Gemini', 'Google Drive'],
    useCases: ['Asistente de equipo', 'Resumen de documentos', 'Automatización desde Slack'],
    complexity: 'Intermedio',
    tags: ['slack', 'gemini', 'ia', 'bot'],
  },
  {
    id: 'wordpress-ai-summaries',
    name: 'AI Summary Blocks para Posts WordPress',
    slug: 'wordpress-ai-summaries',
    category: 'Productividad',
    categorySlug: 'productividad',
    description: 'Genera automáticamente bloques de resumen con IA para todos los posts de WordPress: meta descriptions, excerpts y summaries optimizados para SEO.',
    integrations: ['WordPress API', 'OpenAI', 'n8n'],
    useCases: ['Optimización SEO', 'Resúmenes de posts', 'Meta descriptions automáticas'],
    complexity: 'Básico',
    tags: ['wordpress', 'seo', 'ia', 'blog'],
  },
  {
    id: 'customer-support-workflow',
    name: 'Customer Support Workflow Completo',
    slug: 'customer-support-workflow',
    category: 'Productividad',
    categorySlug: 'productividad',
    description: 'Flujo completo de soporte al cliente: recibe consultas, las clasifica por urgencia, genera respuestas automáticas y escala casos complejos.',
    integrations: ['Gmail', 'OpenAI', 'Slack', 'Airtable'],
    useCases: ['Soporte automatizado', 'Clasificación de consultas', 'Escalado inteligente'],
    complexity: 'Intermedio',
    tags: ['soporte', 'cliente', 'automatización', 'ia'],
    isPremium: true,
  },
]
